app:
	# g++ -std=c++11 sender.cpp -o sender.out
	# g++ -std=c++11 receiver.cpp -o receiver.out
	gcc sender.cpp -o sender.out -lrt
	gcc receiver.cpp -o receiver.out -lrt
clean:
	rm sender.out
	rm receiver.out